### ISSUE TITLE
请尽快跟进0.74.0

### ISSUE THREAD

**Issue by Aurora-Simba** [zetaloop/PowerToys-CN#21]
如题

**Comment by zetaloop** [comment]
0.74.0 于 14 小时前发布，我已知晓，请勿着急。
由于大学课程原因，我安排于今天晚上准备适配，手动合并 0.74.0 的更新。
如果遇到新工具，或者一些影响到翻译文本的复杂更改，完成可能会延后。

**Comment by zetaloop** [comment]
完成后会在这里回复你

**Comment by zetaloop** [comment]
已经好啦~

**Comment by Aurora-Simba** [comment]
> 已经好啦~

感谢您的付出
