### ISSUE TITLE
请求翻译0.79.0版本

### ISSUE THREAD

**Issue by srxqds** [zetaloop/PowerToys-CN#22]

**Comment by zetaloop** [comment]
正在制作的

**Comment by zetaloop** [comment]
![image](https://github.com/zetaloop/PowerToys-CN/assets/36418285/10957408-18d9-4e7b-bae6-de16ea585f82)
周五要补考高数，我先复个习，没有问题的话周末可能能好

**Comment by zetaloop** [comment]
哇好久没人来催我更新了耶，你是近几个月第一个噢~

**Comment by srxqds** [comment]
感谢贡献

**Comment by srxqds** [comment]
> ![image](https://private-user-images.githubusercontent.com/36418285/310839751-10957408-18d9-4e7b-bae6-de16ea585f82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MDg1MzgsIm5iZiI6MTcwOTgwODIzOCwicGF0aCI6Ii8zNjQxODI4NS8zMTA4Mzk3NTEtMTA5NTc0MDgtMThkOS00ZTdiLWJhZTYtZGUxNmVhNTg1ZjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDEwNDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNTRjYTQ5YTIzZWQxMjRhOTNiOWZkYjkzYjZmNTc1MzA1M2JiOTg4ZmJhYjdjZTkwZmEzZDE1NWU5ZmM4YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T0q7QQ8BA1qgAgNabSnoVCgOx2WaSrJuRCNhmHGPax8) 周五要补考高数，我先复个习，没有问题的话周末可能能好

你也用beyound compare，你用的是破解版？

**Comment by zetaloop** [comment]
> 你也用beyound compare

新旧对比差异合并确实快很多，PowerToys这边的汉化有一些要手动改，用git合并不方便。

> 你用的是破解版？

正版太贵了没钱买😂

**Comment by zetaloop** [comment]
好消息，0.79.0 完成啦~
~~坏消息，补考没过~~
