### ISSUE TITLE
请求更进版本0.85.0

### ISSUE THREAD

**Issue by Counta** [zetaloop/PowerToys-CN#23]
为0.84.0套用0.83.0的补丁后 各项功能可以使用 但所有GUI界面无法打开

**Comment by zetaloop** [comment]
感谢厚爱，我最近笔记本电脑拿去维修了，所以进度拖迟了，明天应该能继续。

不同版本补丁不能混用，版本不对的话加载不了的。

**Comment by zetaloop** [comment]
正在制作 :)

**Comment by zetaloop** [comment]
PT v0.85.1 汉化做完啦
