### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by martjay** [zetaloop/PowerToys-CN#24]
双击bat和右键管理员身份运行一闪而过，建议打包exe安装包

**Comment by zetaloop** [comment]
试试用这个版本，看看在哪一步出现了问题。
[点击下载 v20test1.zip](https://github.com/user-attachments/files/17323967/v20test1.zip)
请用管理员权限打开终端，然后在终端里运行 `安装debug2.CMD`。

也请检查，汉化包是否是被杀毒软件拦截了。

此外，直接打包成 exe 可能不太行，一些组件在官方构建里似乎是不太一样的。以及安装包太大了，网盘放不下。

**Comment by martjay** [comment]
> 试试用这个版本，看看在哪一步出现了问题。 [点击下载 v20test1.zip](https://github.com/user-attachments/files/17323967/v20test1.zip) 请用管理员权限打开终端，然后在终端里运行 `安装debug2.CMD`。
> 
> 也请检查，汉化包是否是被杀毒软件拦截了。
> 
> 此外，直接打包成 exe 可能不太行，一些组件在官方构建里似乎是不太一样的。以及安装包太大了，网盘放不下。

用了这个包我才发现原来我是没安装原版软件，哈哈哈，抱歉

**Comment by zetaloop** [comment]
噢！我还真没考虑过PT未安装这个情况，下次如果检测到未安装，我会加一个弹窗提示的。

**Comment by martjay** [comment]
> 噢！我还真没考虑过PT未安装这个情况，下次如果检测到未安装，我会加一个弹窗提示的。

感谢汉化，做的非常好
